from . import account_invoice
from . import custom_fields
from . import crm_lead
from . import hr_employee
from . import purchase_order
from . import sale_order
from . import res_company
from . import res_partner
from . import emp_details
from . import invoice_hsn_code
from . import sale_order1
from . import purchase_order1
from . import emp_type
